language: android
jdk: oraclejdk8
sudo: required
android:
  components:
    - tools
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
    - build-tools-26.0.2
    - android-26

before_install:
- yes | sdkmanager "platforms;android-27"

script: "./gradlew build --stacktrace"